on:
  push:
    branches:
      - main

jobs:
  print_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world!
      - run: echo "Hello World!"
      - name: test
      - run: mvn test
